Add RTK v2 support
LORD-MicroStrain/microstrain_inertial_driver_common pull request #9
Opened 2022-01-19 19:08 UTC by dacuster

2022-01-19 19:25 UTC, robbiefish requested changes
Looks mostly good for ROS, but does this does not appear to have changes required for ROS2 yet. This just requires adding the proper `using` statements into the `microstrain_defs.h` file

2022-01-19 19:25 UTC, robbiefish commented on src/microstrain_config.cpp
> +    inertial_device_->setActiveChannelFields(mscl::MipTypes::DataClass::CLASS_GNSS3, supportedChannels);
I would pull the `main` branch into your fork as this has already been updated and should not be showing up as a difference

2022-01-19 19:27 UTC, dacuster commented
Forgot this was common to ROS2 as well. I'll work on that shortly

2022-01-21 19:18 UTC, robbiefish requested changes
This now works well for both ROS and ROS2.

I would just add some documentation to the [`rtk_dongle_enable` parameter in params.yml](https://github.com/LORD-MicroStrain/microstrain_inertial_driver_common/blob/main/config/params.yml#L123) that explains that enabling this option will also cause the node to publish on one of two different topics depending on the version of the RTK dongle connected to the GQ7

2022-01-25 20:52 UTC, robbiefish approved these changes

2022-01-25 20:52 UTC, merged